### ISSUE TITLE
Hey👋, can you also add a title editor to the video editor? [Эй👋, а можно еще добавить редактор титров в видеоредактор?]

### ISSUE THREAD

**Issue by JeelTikiwala** [MrCheatEugene/SVEdit#1]
Hey👋, can you also add a title editor to the video editor and mine shows ffmpeg load error.
 [Эй👋, вы можете также добавить редактор титров в видеоредактор, а мой показывает ошибку загрузки ffmpeg]

**Comment by MrCheatEugene** [comment]
Hi. What is the error?
It is shown in DevTools console. 
Copy it, or just attach a screenshot. 
I will add an title editor in next release.
